# A Brief Description of Dynamic Programming

## Matrix Chain Multiplication

**Using Generic Recursion** $O(N^N)$

In [28]:
N = 4 # Number of Metrics
P = [5,4,6,2,7] # Dimentsion vector

def Matrix_Chain(x, y): # x and y denotes the cost of product of x,x+1,x+2...y metrices in sequence
    if x==y: 
        return 0
    L = []
    for i in range(x, y):
        L.append(Matrix_Chain(x, i)+Matrix_Chain(i+1, y)+P[x-1]*P[i]*P[y])
    return min(L)

print('Answer :', Matrix_Chain(1,4))

Answer : 158


**Recursion with Memorization** $O(N^3)$

In [31]:
import numpy

N = 4 # Number of Metrics
P = [5,4,6,2,7] # Dimentsion vector

R = numpy.ones([N+1, N+1])*-1 # Reference matrix (1-indexed)

def Matrix_Chain(x, y): # x and y denotes the cost of product of x,x+1,x+2...y metrices in sequence
    if x==y: 
        return 0
    
    if R[x][y] != -1: # Memorization step
        return R[x][y]

    L = []
    for i in range(x, y):
        L.append(Matrix_Chain(x, i)+Matrix_Chain(i+1, y)+P[x-1]*P[i]*P[y])
    R[x][y] = min(L)

    return R[x][y]

print('Answer :', Matrix_Chain(1,4))
print(R)

Answer : 158.0
[[ -1.  -1.  -1.  -1.  -1.]
 [ -1.  -1. 120.  88. 158.]
 [ -1.  -1.  -1.  48. 104.]
 [ -1.  -1.  -1.  -1.  84.]
 [ -1.  -1.  -1.  -1.  -1.]]


**Standard Iterative Dynamic Programming** $O(N^3)$

In [19]:
import numpy

N = 4 # Number of Metrics
P = [5,4,6,2,7] # Dimentsion vector

M = numpy.zeros([N+1, N+1]) # Output matrix (1-indexed)
# Initialization -> set M[i,i] = 0 for all vaild i

# filling start from M[1,2] -> M[2,3] -> M[3, 4] -> M[1,3] -> M[2, 4] -> M[1, 4] (in digonal fashion)
x, y, d = 1, 2, 2
while(True): 
    if x < y:
        L = [] 
        for i in range(x, y):L.append(M[x][i]+M[i+1][y]+P[x-1]*P[i]*P[y])
        M[x][y]=min(L)
    if x == 1 and y == N : break
    x, y = x+1, y+1
    if y > N : x, y, d = 1, d+1, d+1

print('Answer :', M[1][N])   # Result at M[1, N]   
print(M)

Answer : 158.0
[[  0.   0.   0.   0.   0.]
 [  0.   0. 120.  88. 158.]
 [  0.   0.   0.  48. 104.]
 [  0.   0.   0.   0.  84.]
 [  0.   0.   0.   0.   0.]]


<hr>

## Longest Common Subsequence

**Generic Recursion** $O(2^N)$

In [11]:
A = ' STONE' # first string (one indexed)
B = ' LONGEST' # second string (one indexed)

def LCS(i, j): # i and j represents the indices of strings A and B respectively
    if i == 0 or j == 0:
        return 0
    if A[i]==B[j]:
        return 1 + LCS(i-1, j-1)
    else:
        return max(LCS(i, j-1), LCS(i-1, j))

print("Answer :", LCS(len(A)-1, len(B)-1))

Answer : 3


**Recursion with Memorization** $O(M\times N)$

In [15]:
import numpy

A = ' STONE' # first string (one indexed)
B = ' LONGEST' # second string (one indexed)

R = numpy.ones([len(A),len(B)])*-1 # reference matrix (one indexed)

def LCS(i, j): # i and j represents the indices of strings A and B respectively
    if i == 0 or j == 0:
        return 0

    if R[i][j] != -1: # memorization step
        return R[i][j]

    if A[i]==B[j]:
        R[i][j] = 1 + LCS(i-1, j-1)
    else:
        R[i][j] = max(LCS(i, j-1), LCS(i-1, j))
    
    return R[i][j]

print("Answer :", LCS(len(A)-1, len(B)-1))
print(R)

Answer : 3.0
[[-1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  0.  0.  0.  0.  0.  1. -1.]
 [-1.  0.  0.  0.  0.  0.  1.  2.]
 [-1. -1.  1.  1.  1.  1.  1.  2.]
 [-1. -1. -1.  2.  2.  2.  2.  2.]
 [-1. -1. -1. -1. -1.  3.  3.  3.]]


**Standard Iterative Dynamic Programming** $O(M\times N)$

In [23]:
import numpy

A = 'STONE' # first string (one indexed)
B = 'LONGEST' # second string (one indexed)

a = len(A) # length of string A
b = len(B) # length of string B

A = ' ' + A # conversion into one index
B = ' ' + B # conversion into one index

M = numpy.zeros([a+1, b+1]) # output matrix (zero indexed)
# Initialization -> set the first column and first row to zero

for x in range(1, M.shape[0]):
    for y in range(1, M.shape[1]):
        if A[x] == B[y] : M[x][y] = 1 + M[x-1][y-1]
        else : M[x][y] = max(M[x-1][y], M[x][y-1])

print('Answer :', M[a][b]) # Result at M[a][b]
print(M)

Answer : 3.0
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 2.]
 [0. 0. 1. 1. 1. 1. 1. 2.]
 [0. 0. 1. 2. 2. 2. 2. 2.]
 [0. 0. 1. 2. 2. 3. 3. 3.]]


<hr>

## 0/1 Knapsack

**Using Generic Recurision**  $O(2^{N})$

In [23]:
N = 3 # number of objects available
C = 6 # capacit of the knapsack

P = [0, 10, 12, 28] # profit vector (1-indexed)
W = [0, 1, 2, 4]    # weight vector (0-indexed)

def Knapsack(i, c): # i is ref to ith item, c is ref to available capacity
    if c == 0 or i == 0:
        return 0
    if W[i] > c:
        return Knapsack(i-1, c)
    else:
        return max( P[i]+Knapsack(i-1, c-W[i]), Knapsack(i-1,c) )

print('Answer :', Knapsack(N, C))

Answer : 40


**Recusrion with Memorization** $O(N\times C)$

In [21]:
import numpy

N = 3 # number of objects available
C = 6 # capacit of the knapsack

P = [0, 10, 12, 28] # profit vector (1-indexed)
W = [0, 1, 2, 4]    # weight vector (0-indexed)

R = numpy.ones([N+1, C+1])*-1 # Reference matrix (1-indexed)

def Knapsack(i, c): # i is ref to ith item, c is ref to available capacity
    if c == 0 or i == 0:
        return 0
    
    if R[i][c]!=-1 : return R[i][c] # memorization
    
    if W[i] > c : R[i][c] = Knapsack(i-1, c)
    else        : R[i][c] = max( P[i]+Knapsack(i-1, c-W[i]), Knapsack(i-1,c) )
    
    return R[i][c]

print("Answer :", Knapsack(N, C))
print(R) # Resunt in R[N, C]

Answer : 40.0
[[-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. 10. -1. 10. -1. 10.]
 [-1. -1. 12. -1. -1. -1. 22.]
 [-1. -1. -1. -1. -1. -1. 40.]]


**Standard Iterative Dynamic Programming using Table** $O(N\times C)$

In [24]:
import numpy

N = 3 # number of objects available
C = 6 # capacit of the knapsack

P = [0, 10, 12, 28] # profit vector (1-indexed)
W = [0, 1, 2, 4]    # weight vector (0-indexed)

M = numpy.zeros([N+1, C+1]) # output matrix (0-indexed)
# Initialization First Row and First Column is set to 0

for x in range(1,M.shape[0]):  
    for y in range(1,M.shape[1]): # data filling starts from position [1,1]
        if W[x]>y:
            M[x][y] = M[x-1][y]
        else:
            M[x][y] = max( P[x] + M[x-1, y-W[x]], M[x-1][y] )

print('Answer :', M[N][C]) # answer at M[N, C]
print(M) 

Answer : 40.0
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10. 10. 10. 10. 10. 10.]
 [ 0. 10. 12. 22. 22. 22. 22.]
 [ 0. 10. 12. 22. 28. 38. 40.]]


<hr>

## Sum of Subsets

**Generic Recursion** $O()$

In [7]:
E = [0,1,2,3,4] # Element List (One-Indexed)
N = 4 # number of items
S = 7 # required sum

def SubsetSum(i, s): # i refers to the element, w refers to required sum
    if s == 0 : return True
    if i == 0 : return False
    if E[i]>s : return SubsetSum(i-1, s)
    else      : return SubsetSum(i-1, s-E[i]) or SubsetSum(i-1, s)

print('Answer :',SubsetSum(N, S))

Answer : True


**Recursion with Memorization** $O(N\times S)$

In [19]:
import numpy

E = [0,1,2,3,4] # Element List (One-Indexed)
N = 4 # number of items
S = 6 # required sum

R = numpy.ones([N+1, S+1])*-1 # reference matrix, one-indexed

def SubsetSum(i, s): # i refers to the element, w refers to required sum
    if s == 0 : return 1
    if i == 0 : return 0

    if R[i][s] != -1: # memorization step
        return R[i][s]

    if E[i]>s : R[i][s] = SubsetSum(i-1, s)
    else      : R[i][s] = SubsetSum(i-1, s-E[i]) or SubsetSum(i-1, s)
    return R[i][s]

print('Answer :', SubsetSum(N, S) == 1)
print(R)

Answer : True
[[-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  1.]]


**Standard Iterative Dynamic Programming** $O(N\times S)$

In [24]:
import numpy

E = [0,6,3,2,1] # Element List (One-Indexed)
N = 4 # number of items
S = 5 # required sum

M = numpy.zeros([N+1, S+1]) # output matrix, zero-indexed
# Initialization -> Set M[i, 0] = True for all i; M[0, i] = False for all i != 0
for i in range(M.shape[0]): M[i][0] = 1

for x in range(1, M.shape[0]):
    for y in range(1, M.shape[1]):
        if E[x]>y : M[x][y] = M[x-1][y]
        else      : M[x][y] = M[x-1][y-E[x]] or M[x-1][y]

print('Answer :', M[N][S] == 1) # Result at M[N, S] 
print(M)

Answer : True
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 0. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


<hr>

## The Traveling Salesperson Problem

**Generic Recursion** $O(N!)$ or $O(N^N)$

In [3]:
Cost = [[0, 10, 15, 20], [5,  0,  9, 10], [6, 13,  0, 12], [8,  8,  9,  0]] # the cost matrix

def Set_Minus(Set, Element): # function that returns [Set - Element]
    Temp = Set.copy()
    Temp.remove(Element)
    return Temp

def TSP(A, R):
    if len(R) == 0: # that is, R is empty
        return Cost[A][0] # 0 is the source and destination vertex
    L = []
    for K in R:
        L.append(Cost[A][K] + TSP(K, Set_Minus(R, K))) # Set_Minus(R, K) returns R - K
    return min(L)

print('Answer :', TSP(0, [1,2,3]))

Answer : 35


**Recursion with Memorization** 

Unlike other DP Ptoblems, TSP is a NP Complete problem, thus, even after applying DP, the average time complexity is $O(N^2\times 2^N)$

To implement a DP solution, we here use a concept of mask. In order to maintain a table, we need to uniquely identify each subproblem. Each pair of Mask and Current node can be uinquely identified. That is, the pair $(Mask = 1001, Current = 3)$ for N=4 denotes that we are at the Node with index 3 (zero index), and only Nodes 0 and 3 is visited at this point. Similarly, $(Mask = 0001, Current = 0)$ denotes we are at Node 0 (starting Node), and no cities are visited. And, thus $(Mask = 1111, Current = 2)$ denotes we are at node 2, and all the nodes are visisted.

In terms of recurence relation, 1001 denotes [1,2], 1101 denotes [2], 0001 denotes [1,2,3] and 1111 denotes [ ]

Non - Memorization, Masked based TSP

In [25]:
Cost = [[0, 10, 15, 20], [5,  0,  9, 10], [6, 13,  0, 12], [8,  8,  9,  0]] # the cost matrix
N = 4 # total number of vertices

def TSP(Mask, Current):
    if Mask == 2**N - 1:
        return Cost[Current][0]
    L = []
    M = 1
    for K in range(1, N):
        M = M << 1
        if M & Mask == 0:
            L.append(Cost[Current][K] + TSP(M | Mask, K))
    return min(L)

print('Answer :', TSP(1, 0))

Answer : 35


Memorisation and Masked Based TSP

In [3]:
import numpy

Cost = [[0, 10, 15, 20], [5,  0,  9, 10], [6, 13,  0, 12], [8,  8,  9,  0]] # the cost matrix
N = 4 # total number of vertices

Result = numpy.ones([2**N, N])*-1 # Resultanat Matrix, Zero Indexed

def TSP(Mask, Current):
    if Mask == 2**N -1: # if mask is 1111 denotes no node is unvisited
        return Cost[Current][0]
    
    if Result[Mask][Current]!=-1: # memorization step
        return Result[Mask][Current]

    L, M = [], 1
    for K in range(1, N): 
        M = M << 1
        if M & Mask == 0:
            L.append(Cost[Current][K] + TSP(M | Mask, K))
    Result[Mask][Current] = min(L) # memorization step

    return Result[Mask][Current]

print('Answer :', TSP(1,0))
print(Result)

Answer : 35.0
[[-1. -1. -1. -1.]
 [35. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. 25. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. 25. -1.]
 [-1. -1. -1. -1.]
 [-1. 18. 20. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. 23.]
 [-1. -1. -1. -1.]
 [-1. 15. -1. 15.]
 [-1. -1. -1. -1.]
 [-1. -1. 18. 13.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


<hr>

## All Pair Shortest Path - Floyd Warshall

**Table Based Iterative DP** $O(N^3)$

In [23]:
import numpy

inf = 100

Cost = [[inf,inf,inf,inf,inf],[inf,0,11,1,6],[inf,11,0,7,3],[inf,1,7,0,2],[inf,6,3,2,0]] # Cost Adjecienct Matrix (1-index)
N = 4 # number of vertices

D = numpy.array([N+1,N+1]) # Resultant Matrix, one-indexed

for k in range(0,N+1): 
    A = numpy.ones([N+1,N+1])*inf
    for i in range(1,N+1):
        for j in range(1,N+1):
            if k == 0:
                A[i][j] = Cost[i][j]
            else:
                A[i][j] = min(D[i][j], D[i][k] + D[k][j])
    
    D = numpy.copy(A)
    print(D, ': D['+str(k)+']')

[[100. 100. 100. 100. 100.]
 [100.   0.  11.   1.   6.]
 [100.  11.   0.   7.   3.]
 [100.   1.   7.   0.   2.]
 [100.   6.   3.   2.   0.]] : D[0]
[[100. 100. 100. 100. 100.]
 [100.   0.  11.   1.   6.]
 [100.  11.   0.   7.   3.]
 [100.   1.   7.   0.   2.]
 [100.   6.   3.   2.   0.]] : D[1]
[[100. 100. 100. 100. 100.]
 [100.   0.  11.   1.   6.]
 [100.  11.   0.   7.   3.]
 [100.   1.   7.   0.   2.]
 [100.   6.   3.   2.   0.]] : D[2]
[[100. 100. 100. 100. 100.]
 [100.   0.   8.   1.   3.]
 [100.   8.   0.   7.   3.]
 [100.   1.   7.   0.   2.]
 [100.   3.   3.   2.   0.]] : D[3]
[[100. 100. 100. 100. 100.]
 [100.   0.   6.   1.   3.]
 [100.   6.   0.   5.   3.]
 [100.   1.   5.   0.   2.]
 [100.   3.   3.   2.   0.]] : D[4]


In [5]:
a=numpy.zeros([2,2])
b=numpy.copy(a)
a[0][0]=1
b

array([[0., 0.],
       [0., 0.]])